export const classes = {
    ref: 'link-primary',
    refInvalid: 'link-primary link-invalid',
    displayEquation: 'display-equation',
    blockEnvironment: 'block-container',
    blockTitle: 'link-foreground',
    proof: 'proof',
    proofIntro: '',
    qed: 'qed',
    cite: '',
    citeNote: '',
    citeRef: 'link-primary',
    divisionTitle: 'link-foreground',
    tikz: 'tikz-container',
    figure: 'figure',
    figureCaption: 'figure-caption link-foreground',
    footnoteRef: 'footnote-ref link-primary',
    textAction: 'text-action',
    copyLabel: 'text-action copy-label',
} as const;